### ISSUE TITLE
解析后的链接提示404

### ISSUE THREAD

**Issue by nifanfa** [Entity-Now/LanzouCloudSolve#2]
![image](https://github.com/Entity-Now/LanzouCloudSolve/assets/54205437/4758d27f-71e0-4500-b09a-e34ea8666f31)
![image](https://github.com/Entity-Now/LanzouCloudSolve/assets/54205437/8966a5d9-577c-4fd5-bc40-fbc7e088d234)

**Comment by Entity-Now** [comment]
已修复，更新到1.0.3版本，等待nuget审核通过
